### ISSUE TITLE
I cannot change Element's font.

### ISSUE THREAD

**Issue by siakc** [Solomoriah/PollyReports#5]
I tried Arial an a Farsi font but got the error as follows:
```

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 711, in getFont
    return _fonts[fontName]
KeyError: 'Arial'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "D:/_devs/finautopay/finoautomain.py", line 52, in <module>
    ofilename=dest['ref_code'])
  File "D:/_devs/finautopay\create_receipts.py", line 39, in crerate_pdf
    rpt.generate(canvas)
  File "C:\Python36\lib\site-packages\PollyReports.py", line 548, in generate
    self.current_offset += self.addtopage(canvas, elementlist)
  File "C:\Python36\lib\site-packages\PollyReports.py", line 443, in addtopage
    el.render(self.current_offset, canvas)
  File "C:\Python36\lib\site-packages\PollyReports.py", line 103, in render
    canvas.setFont(*self.font)
  File "C:\Python36\lib\site-packages\reportlab\pdfgen\canvas.py", line 1660, in setFont
    font = pdfmetrics.getFont(self._fontname)
  File "C:\Python36\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 713, in getFont
    return findFontAndRegister(fontName)
  File "C:\Python36\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 695, in findFontAndRegister
    face = getTypeFace(fontName)
  File "C:\Python36\lib\site-packages\reportlab\pdfbase\pdfmetrics.py", line 652, in getTypeFace
    return _typefaces[faceName]
KeyError: 'Arial'
```

**Comment by Solomoriah** [comment]
Looks like you didn't register your Arial font with Reportlab; this is not a PollyReports issue per se.  If you are using a font other than the standard Postscript fonts (Times, Helvetica, Courier, a few others), you have to have the font file(s) handy and register them.

Here's a sample from one of my applications:

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
pdfmetrics.registerFont(TTFont("Arial", "arial.ttf"))
